container:
  image: php
docker_build:
  env:
    matrix:
      - CONTAINER: php
      - CONTAINER: php2
  script:
    #- docker build -t $CONTAINER images/$CONTAINER
    - ls images/$CONTAINER
  skip: "!changesInclude('images/$CONTAINER/*')"

